---
- name: Deploy app stack
  docker_stack:
    name: "{{ app_stack_name }}"
    with_registry_auth: true
    resolve_image: never
    compose:
      - version: '3'
        services:
          redis:
            image: redis:latest
            networks:
              - appnet
          tradeview-listener:
            image: ogorbunov/tradebot:tradeview-listener-latest
            environment:
              APP_ENV: 'production'
              APP_DEBUG: 1
              APP_HOST: '0.0.0.0'
              APP_PORT: 80
              APP_TIMEZONE: 'UTC'
              DNS_RESOLVER_HOST: '127.0.0.11'
              DB_HOSTNAME: 'database'
              DB_PORT: 3306
              DB_USERNAME: 'user'
              DB_PASSWORD: 'password'
              DB_DATABASE: 'database'
              REDIS_HOST: 'redis'
              REDIS_PORT: 6379
            networks:
              - appnet
              - traefiknet
            deploy:
              labels:
                - "traefik.enable=true"
                - "traefik.http.routers.tradeview-listener.rule=Host(`tradeview.{{base_hostname}}`)"
                - "traefik.http.routers.tradeview-listener.entrypoints=websecure"
                - "traefik.http.routers.tradeview-listener.tls.certresolver=tlsresolver"
                - "traefik.http.services.tradeview-listener-service.loadbalancer.server.port=80"
                - "traefik.http.routers.tradeview-listener.tls.domains[0].main=tradeview.{{base_hostname}}"
        networks:
          appnet:
            external: true
          traefiknet:
            external: true

